export function getHelpText(): string {
  return [
    "🤖 **Bot Komutları**",
    "",
    "**📊 Fiyat Komutları**",
    "`!fiyat` — En popüler 10 tokenin anlık fiyatı",
    "`!detay` — BTC, PHA, BIO, ONT, KAT için 24 saatlik detay",
    "`!ara <token>` — Herhangi bir tokenin detayı (örn: `!ara SOL`)",
    "",
    "**📈 Piyasa Komutları**",
    "`!yukselenler` — Binance'ta en çok yükselen ilk 10",
    "`!dusenler` — Binance'ta en çok düşen ilk 10",
    "`!piyasa` — Toplam piyasa değeri ve BTC dominansı",
    "`!korku` — Korku & Açgözlülük Endeksi",
    "`!dolar` — Anlık USD/EUR/GBP → TRY kurları",
    "",
    "**⚠️ Alarm Komutları**",
    "`!alarm <token> <fiyat>` — Yükseliş alarmı (örn: `!alarm BTC 100000`)",
    "`!alarm <token> <fiyat> altı` — Düşüş alarmı (örn: `!alarm BTC 80000 altı`)",
    "`!alarm listesi` — Aktif alarmlarını göster",
    "`!alarm sil <token>` — Alarm sil (örn: `!alarm sil BTC`)",
    "",
    "**💼 Portföy Komutları**",
    "`!portfoy` — Portföyümü göster (anlık değerle)",
    "`!portfoy ekle <token> <miktar>` — Token ekle (örn: `!portfoy ekle BTC 0.5`)",
    "`!portfoy çıkar <token>` — Token çıkar (örn: `!portfoy çıkar BTC`)",
    "`!portfoy sıfırla` — Tüm portföyü sıfırla",
    "",
    "**👋 Karşılama & Davet**",
    "`!hosgeldin-kur` — Bu kanalda yeni üyeleri otomatik karşıla",
    "`!hosgeldin-kur kapat` — Karşılama mesajlarını kapat",
    "`!davet` — Kişisel davet linkin + kaç kişi davet ettiğin",
    "",
    "**📅 Günlük Rapor**",
    "`!rapor-kur` — Bu kanalda her sabah 09:00 otomatik rapor başlat",
    "`!rapor-kur kapat` — Günlük raporu kapat",
    "",
    "**🎮 Demo Trading Oyunu**",
    "`!bakiye` — Demo bakiyeni ve kâr/zararını gör",
    "`!günlük` — Günlük ödül al ($50-$500 + seri bonusu 🔥)",
    "`!al <token> <dolar>` — Token satın al (örn: `!al BTC 500`)",
    "`!sat <token> <dolar>` — Token sat (örn: `!sat BTC 200`)",
    "`!demo` — Demo portföyünü ve K/Z'ni gör",
    "`!sıralama` — En iyi trader sıralaması 🏆",
    "`!demo-sifirla` — Hesabı $10.000 ile baştan başlat",
  ].join("\n");
}
